services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=liza
      - POSTGRES_USER=liza
      - POSTGRES_DB=player_db
    ports:
      - 5432:5432
    volumes:
      - ~/intuit/player/postgres:/var/lib/postgresql/data

  app:
    volumes:
      - ~/intuit/player/src/main/resources:/root/intuit/player/src/main/resources
    network_mode: host
    image: player
    build:
      context: .
